### ISSUE TITLE
Fails to compile when following instructions from wiki

### ISSUE THREAD

**Issue by GodlikeRU** [matlo/GIMX-build#1]
Hello,

I think I discovered a pretty severe bug  in `build.sh`. This script automates building gimx by downloading it from git, compiling, etc. If I clone this repository using instructions from wiki - https://gimx.fr/wiki/index.php?title=Development_on_Windows

By this command:
`./build.sh`
It will throw:
`make[2]: Leaving directory '/home/Godlike/GIMX-build/windows/GIMX/shared/gimxconfigupdater'
make -C gimxlog UHID=
make[2]: Entering directory '/home/Godlike/GIMX-build/windows/GIMX/shared/gimxlog'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory '/home/Godlike/GIMX-build/windows/GIMX/shared/gimxlog'
make[1]: *** [Makefile:19: build-gimxlog] Error 2
make[1]: Leaving directory '/home/Godlike/GIMX-build/windows/GIMX/shared'
make: *** [Makefile:15: build-shared] Error 2
make: Leaving directory '/home/Godlike/GIMX-build/windows/GIMX'`

It throws an error because in fact `shared/gimxlog` folder is completely empty. Git command lacks `--recursive` and it doesn't downloads submodules like **gimxlog**, **gimxprio** and so on.

build.sh needs to be modified in order to fix this issue. Im making a pull request with fix. It's really small and it fixes the compilation issue.

**Steps to reproduce issue:**

1. Clone the repository to the fresh folder
2. Try to build it

My OS is Windows 10 1607 x64
Using  msys2-x86_64-20161025

Regards,
Daniel

**Comment by matlo** [comment]
Thanks.
